# Generated by Django 5.0.6 on 2024-05-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='time_upadate',
            new_name='time_update',
        ),
    ]
